baseURL = "https://YOUR-SITE.netlify.app/"
title = "Mario Sambol"
languageCode = "en"
paginate = 20
theme = ["github.com/luizdepra/hugo-coder"]   # theme via Hugo Modules

[module]
  [[module.imports]]
    path = "github.com/luizdepra/hugo-coder"

[params]
  author = "Mario Sambol"
  description = "Personal site"
  colorScheme = "auto"
  avatarURL = "images/avatar.jpg"   # if you add one to /static/images/

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url  = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 3

